### ISSUE TITLE
missing `npm install express --save` ?

### ISSUE THREAD

**Issue by sebastianconcept** [danawoodman/docker-node-hello-world#2]

**Comment by danawoodman** [comment]
@sebastianconcept I'm confused what you're referring to. This doesn't use express, it just uses the built in Node HTTP server. Let me know if I'm missing something...

**Comment by sebastianconcept** [comment]
Puh, my bad @danawoodman ! sorry for the confussion

**Comment by danawoodman** [comment]
No problem! 😉
